### ISSUE TITLE
Auto version checker

### ISSUE THREAD

**Issue by Titaniumtown** [Titaniumtown/TitaniumMC#6]
From the discord server's #development channel:
> I have an idea for a patch that like every hour checks to see how old the server is, and if the server is, lets say, 5+ commits behind master, it prints a warning to update. and if it's detected that the server is 5+ commits behind during startup, it'll prevent the server from loading printing a message about needing to update

Edit: No longer going to prevent the server from starting, only periodic warnings every 30 minutes.

**Comment by tobfos2611** [comment]
Making the server not start is too far.

**Comment by Titaniumtown** [comment]
There would be a JVM flag you would set to override it if necessary (for testing purposes). But the idea is to force server owners to update their servers, which a lot don't do very often.

**Comment by tobfos2611** [comment]
Okay, but the problem is that sometimes the server owner may be offline for a while and not be able to update the server and 9 the server won't launch.

**Comment by Titaniumtown** [comment]
Good point. I'll only do a warning that the server is out of date every 30 mins or so then.

**Comment by tobfos2611** [comment]
And no shutting down of the server?

**Comment by Titaniumtown** [comment]
> Edit: No longer going to prevent the server from starting, only periodic warnings every 30 minutes.
